// <auto-generated />
using Korepetycje_Matematyka.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Korepetycje_Matematyka.Migrations
{
    [DbContext(typeof(DbContextAccount))]
    partial class DbContextAccountModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Korepetycje_Matematyka.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Korepetycje_Matematyka.Data.Terminy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dzień_Tygodnia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Godzina9")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Terminy");
                });
#pragma warning restore 612, 618
        }
    }
}
